package report

import (
	"fmt"

	"github.com/easonliuuuuu/vsfleet/internal/assessment"
	"github.com/easonliuuuuu/vsfleet/internal/health"
)

// This file describes what the rvtools export profile writes: every worksheet,
// every column, the unit and type of each cell, and when a cell is left empty.
//
// It describes what vsfleet emits and flags observed value differences from
// one RVTools 4.8.1.4 comparison. It does not enumerate columns RVTools has
// that this profile does not: that would require a reference copy of a
// proprietary schema, which this project does not have. A pipeline owner
// compares the emitted fields against their own requirements.
//
// Profile is generated by walking the real exporter output, and
// TestEveryExportedColumnIsDocumented fails the build if a column is added to a
// worksheet without describing it here. The report and the workbook therefore
// cannot drift apart.

// Cell kinds. These describe what a reader will find in the cell, in both the
// XLSX and CSV renderings — csvCell is the authority on how each is textualized.
const (
	KindText    = "text"
	KindInteger = "integer"
	KindDecimal = "decimal"
	KindBoolean = "boolean"
	KindDate    = "date"
)

// ColumnSpec describes one column of one worksheet.
type ColumnSpec struct {
	Name string `json:"column"`
	Kind string `json:"kind"`
	// Unit is the unit of measure, empty for unitless values.
	Unit string `json:"unit,omitempty"`
	// Empty says when the cell is left empty, empty itself when the column is
	// always populated.
	Empty string `json:"empty,omitempty"`
	Note  string `json:"note,omitempty"`
}

// SheetSpec describes one worksheet of the export.
type SheetSpec struct {
	Name string `json:"sheet"`
	// Compatible reports whether the worksheet is one of the RVTools-named
	// layouts this profile renders. vsfleetCoverage is vsfleet's own.
	Compatible bool `json:"rvtools_named"`
	// DerivesFrom names the collection the rows come from, matching the
	// vsfleetCoverage sheet's own accounting.
	DerivesFrom string       `json:"derives_from"`
	Note        string       `json:"note,omitempty"`
	Columns     []ColumnSpec `json:"columns"`
}

// Profile returns the full description of the rvtools export profile.
//
// It walks the actual sheet definitions rather than a parallel list: passing
// zero data through the exporter yields every worksheet with its real header
// row and no rows, which is the enumeration this report needs and cannot get
// out of step with.
func Profile() ([]SheetSpec, error) {
	sheets, err := rvtoolsSheets(assessment.ExportData{}, health.Report{})
	if err != nil {
		return nil, err
	}
	out := make([]SheetSpec, 0, len(sheets))
	for _, s := range sheets {
		meta := sheetMeta[s.name]
		spec := SheetSpec{
			Name:        s.name,
			Compatible:  s.name != coverageSheetName && s.name != performanceSheetName,
			DerivesFrom: meta.derivesFrom,
			Note:        meta.note,
			Columns:     make([]ColumnSpec, 0, len(s.headers)),
		}
		for _, header := range s.headers {
			col, ok := describeColumn(s.name, header)
			if !ok {
				return nil, fmt.Errorf("worksheet %s column %q has no description in compatibility.go", s.name, header)
			}
			spec.Columns = append(spec.Columns, col)
		}
		out = append(out, spec)
	}
	return out, nil
}

// describeColumn resolves one column, preferring a per-sheet description over
// the shared one. Names repeat across worksheets — "Capacity MiB" is a virtual
// disk on vDisk, a guest filesystem on vPartition and a datastore on
// vDatastore — so a shared table alone would describe some of them wrongly.
func describeColumn(sheet, name string) (ColumnSpec, bool) {
	if overrides, ok := sheetColumns[sheet]; ok {
		if col, ok := overrides[name]; ok {
			col.Name = name
			return col, true
		}
	}
	col, ok := sharedColumns[name]
	if !ok {
		return ColumnSpec{}, false
	}
	col.Name = name
	return col, true
}

type sheetInfo struct {
	derivesFrom string
	note        string
}

var sheetMeta = map[string]sheetInfo{
	"vInfo": {derivesFrom: "the VM collection", note: "One row per VM and per template."},
	"vCPU":  {derivesFrom: "the VM collection", note: "One row per VM. Configured vCPU count; this profile does not collect CPU performance counters. Measured CPU usage and CPU ready live on the vsfleetPerformance sheet."},
	"vMemory": {derivesFrom: "the VM collection",
		note: "One row per VM. Configured memory only; ballooned, shared and swapped figures are runtime performance counters this read-only profile does not request. Measured active, consumed, ballooned and swapped memory live on the vsfleetPerformance sheet."},
	"vDisk": {derivesFrom: "the VM collection",
		note: "One row per virtual disk. Capacity is what vSphere provisioned; how much of it the guest has used is on vPartition, which vSphere cannot see without VMware Tools."},
	"vPartition": {derivesFrom: "the VM collection",
		note: "One row per guest filesystem. Only VMware Tools inside the guest can measure this, so a powered-off VM, or one whose Tools are not running, contributes no rows at all. vsfleetCoverage marks the tab partial and names how many VMs answered, so a short tab is never mistaken for a small estate."},
	"vNetwork": {derivesFrom: "the VM collection", note: "One row per virtual NIC."},
	"vCD":      {derivesFrom: "the VM collection", note: "One row per virtual CD/DVD device. Connection and backing fields are preserved as unknown when vSphere omits them; captures before inventory schema 6 mark the sheet not recorded in vsfleetCoverage."},
	"vUSB":     {derivesFrom: "the VM collection", note: "One row per virtual USB device. Connection and backing fields are preserved as unknown when vSphere omits them; captures before inventory schema 6 mark the sheet not recorded in vsfleetCoverage."},
	"vTools":   {derivesFrom: "the VM collection", note: "One row per VM. Captures taken before inventory schema 3 populate the running status but leave the version columns blank, and vsfleetCoverage records the gap."},
	"vSource": {derivesFrom: "the stored ServiceInstance About record",
		note: "One row per context whose run stored the vCenter or ESXi ServiceInstance About record at capture time, using the RVTools 4.8.2 vSource column names and order plus a vsfleet Context column. Rows come only from that stored evidence: re-exporting never contacts the server or reads current configuration. A context that never connected, and every run captured before inventory schema 17, has no row; vsfleetCoverage marks the tab failed or not recorded and states why. Fields the server does not report are empty. Not yet compared against a real RVTools 4.8.2 export from the same lab (see docs/assessments.md)."},
	"vHost":      {derivesFrom: "the host collection", note: "One row per ESXi host."},
	"vHBA":       {derivesFrom: "the host collection", note: "One row per host bus adapter. This profile reports adapter identity, transport details and protocol-specific names; it does not issue storage-system queries for target inventory."},
	"vNIC":       {derivesFrom: "the host collection", note: "One row per physical NIC. Link speed is empty when the link is down. Distributed-switch membership is collected on dvSwitch and dvPort."},
	"vSwitch":    {derivesFrom: "the host collection", note: "One row per standard virtual switch, including its effective security policy. Distributed virtual switches are on the separate dvSwitch sheet."},
	"vPort":      {derivesFrom: "the host collection", note: "One row per standard-switch port group. Security values are the effective computed policy after switch inheritance; distributed port groups are on dvPort."},
	"dvSwitch":   {derivesFrom: "the distributed switch collection", note: "One row per distributed virtual switch. Configuration and membership are collected from read-only vSphere properties; per-port runtime state is outside this profile."},
	"dvPort":     {derivesFrom: "the distributed switch collection", note: "One row per distributed port group and its default port policy, not one distributed port. Per-port runtime state is outside this read-only profile."},
	"vSC_VMK":    {derivesFrom: "the host collection", note: "One row per VMkernel or legacy service-console adapter. IP fields are empty when the host does not report them; distributed-switch-only connections are not expanded."},
	"vMultiPath": {derivesFrom: "the host collection", note: "One row per host and SCSI LUN with aggregate path states. Individual paths are counted rather than expanded, and this profile does not collect a separate target inventory."},
	"vCluster":   {derivesFrom: "the cluster collection", note: "One row per cluster. Standalone hosts appear as their own compute resource."},
	"vRP": {derivesFrom: "the resource pool collection",
		note: "One row per resource pool, including each cluster or standalone host's root Resources pool. vApps are reported on their own terms and are not duplicated here. Identity and CPU/memory allocation configuration only: this read-only capture does not request volatile runtime fields rather than guess at them. Captures before inventory schema 8 mark the tab not recorded."},
	"vDatastore": {derivesFrom: "the datastore collection", note: "One row per datastore."},
	"vSnapshot":  {derivesFrom: "the VM collection", note: "One row per snapshot, oldest first within a VM."},
	"vHealth": {derivesFrom: "the health rule engine",
		note: "One row per finding. Derived at export time from the stored evidence rather than collected, so re-exporting an unchanged run reproduces it exactly. assessment export always evaluates with the default thresholds; the tuning flags on `vsfleet health` do not apply to an export."},
	performanceSheetName: {derivesFrom: "the performance ledger",
		note: "A vsfleet extension, not an RVTools worksheet. One row per VM per counter from the newest bounded performance collection of each vCenter, collected separately from the inventory run by `vsfleet assessment perf collect`; the Window start and Window end columns say which period it covers. Values are averages over the vCenter's roll-up interval, so a Peak is the highest interval average, not an instantaneous maximum. An empty statistic is unknown, never zero: read Status and Reason. A vCenter with no collection has one \"not collected\" row. Sizing signals are simulator-validated only until a real-vSphere validation is recorded (see docs/assessments.md)."},
	coverageSheetName: {derivesFrom: "the run ledger",
		note: "A vsfleet extension, not an RVTools worksheet. One row per worksheet per vCenter, naming what collected, what failed, and why. A partial estate is reported as partial rather than handed over as if it were whole."},
}

// sharedColumns describes every column whose meaning does not change between
// worksheets. The identity and provenance tail — Annotation through vsfleet
// Context — is the bulk of it, repeated on every per-VM tab.
var sharedColumns = map[string]ColumnSpec{
	// Per-VM identity and provenance tail.
	"VM":                                     {Kind: KindText, Note: "VM name as vCenter reports it; not unique across an estate."},
	"Powerstate":                             {Kind: KindText, Note: "poweredOn, poweredOff or suspended."},
	"Template":                               {Kind: KindBoolean, Note: "True for a VM template."},
	"Annotation":                             {Kind: KindText, Empty: "when the VM has no notes", Note: "Free text; may contain newlines."},
	"Datacenter":                             {Kind: KindText},
	"Cluster":                                {Kind: KindText, Empty: "for a VM on a standalone host"},
	"Host":                                   {Kind: KindText, Empty: "when vCenter reports no placement"},
	"Folder":                                 {Kind: KindText, Note: "Inventory path below the datacenter's vm folder; the root is /. RVTools 4.8.1.4 includes the datacenter name in this path."},
	"OS according to the configuration file": {Kind: KindText, Note: "The configured guest OS identifier, which is what the VM claims to be — not what the guest actually runs."},
	"VM ID":                                  {Kind: KindText, Note: "vCenter managed object reference, e.g. vm-1042. Unique within one vCenter, not across an estate."},
	"VM UUID":                                {Kind: KindText, Note: "Instance UUID: unique to this VM instance, and the identifier vsfleet tracks a VM by across captures."},
	"VM SMBIOS UUID": {Kind: KindText, Empty: "when vCenter does not report one",
		Note: "The BIOS UUID the guest sees. It is preserved by a clone, so it is not a reliable unique key."},
	"VI SDK Server":   {Kind: KindText, Note: "The configured endpoint, including its URL scheme (for example https://192.168.150.10), not a value vCenter reported. RVTools 4.8.1.4 writes the host without the scheme."},
	"VI SDK UUID":     {Kind: KindText, Note: "The vCenter instance UUID, falling back to the endpoint string when vCenter omits it."},
	"vsfleet Context": {Kind: KindText, Note: "A vsfleet addition present on every worksheet: which configured context the row came from. It is what makes a single estate-wide workbook readable."},

	// vInfo.
	"Guest state":        {Kind: KindText, Empty: "when VMware Tools is not running", Note: "running or notRunning, as reported by Tools."},
	"CPUs":               {Kind: KindInteger, Note: "Configured vCPU count."},
	"Memory":             {Kind: KindInteger, Unit: "MiB", Note: "Configured memory."},
	"Primary IP Address": {Kind: KindText, Empty: "when VMware Tools reports no address"},
	"In Use MiB":         {Kind: KindDecimal, Unit: "MiB", Note: "Committed storage across every disk, as vCenter reports it. Fractional MiB are retained; RVTools 4.8.1.4 writes integer MiB."},

	// vMemory.
	"Size MiB": {Kind: KindInteger, Unit: "MiB", Note: "Configured memory."},

	// vTools.
	"Tools":                {Kind: KindText, Note: "VMware Tools running status (GuestInfo.toolsRunningStatus), for example guestToolsNotRunning. RVTools 4.8.1.4 uses Tools installation status here, for example toolsNotInstalled. Do not treat these values as equivalent."},
	"Tools Version":        {Kind: KindText, Empty: "for a capture predating inventory schema 3, or when vCenter reports no version"},
	"Tools Version Status": {Kind: KindText, Empty: "for a capture predating inventory schema 3", Note: "e.g. guestToolsCurrent, guestToolsNeedUpgrade."},

	// vDisk.
	"Disk UUID":              {Kind: KindText, Empty: "when vSphere does not expose one"},
	"Disk Mode":              {Kind: KindText, Note: "e.g. persistent, independent_persistent."},
	"Sharing mode":           {Kind: KindText, Empty: "when vSphere does not expose one"},
	"Raw":                    {Kind: KindBoolean, Note: "True for a raw device mapping."},
	"Thin":                   {Kind: KindBoolean, Empty: "for a raw device mapping, where it does not apply"},
	"Eagerly Scrub":          {Kind: KindBoolean, Empty: "when vSphere does not expose it"},
	"Split":                  {Kind: KindBoolean, Empty: "when vSphere does not expose it"},
	"Write Through":          {Kind: KindBoolean, Empty: "when vSphere does not expose it"},
	"Controller":             {Kind: KindText, Empty: "when the controller cannot be resolved"},
	"SCSI label":             {Kind: KindText, Empty: "when the controller cannot be resolved"},
	"Unit number":            {Kind: KindInteger, Empty: "when vSphere does not expose one"},
	"Shared Bus":             {Kind: KindText, Empty: "when the controller cannot be resolved", Note: "SCSI controller bus sharing mode, such as noSharing."},
	"Path":                   {Kind: KindText, Empty: "when the disk has no backing file", Note: "Datastore path, e.g. [datastore1] vm/vm.vmdk."},
	"Raw LUN ID":             {Kind: KindText, Empty: "for anything but a raw device mapping"},
	"Raw Compatibility Mode": {Kind: KindText, Empty: "for anything but a raw device mapping"},
	"Level":                  {Kind: KindText, Note: "Disk shares level: low, normal, high or custom."},
	"Shares":                 {Kind: KindInteger, Empty: "when vSphere does not expose it", Note: "Disk shares value."},
	"Reservation":            {Kind: KindInteger, Unit: "IOPS", Empty: "when vSphere does not expose it"},
	"Limit":                  {Kind: KindInteger, Unit: "IOPS", Empty: "when unlimited", Note: "-1 means unlimited where vSphere reports it that way."},

	// vPartition.
	"Consumed MiB": {Kind: KindDecimal, Unit: "MiB", Note: "Fractional MiB are retained; RVTools 4.8.1.4 writes integers. Clamped to zero if VMware Tools reports free space exceeding capacity."},
	"Filesystem":   {Kind: KindText, Empty: "when VMware Tools does not report a type"},

	// vNetwork.
	"NIC label":        {Kind: KindText, Note: "e.g. Network adapter 1."},
	"Adapter":          {Kind: KindText, Note: "Virtual adapter type, e.g. VirtualVmxnet3."},
	"Network":          {Kind: KindText, Empty: "when the NIC is not attached", Note: "Port group name. This profile does not collect VLAN identifiers."},
	"Connected":        {Kind: KindBoolean, Note: "Whether the NIC is connected now."},
	"Starts Connected": {Kind: KindBoolean, Note: "Whether the NIC connects at power on."},
	"Mac Address":      {Kind: KindText},
	"Mac Address type": {Kind: KindText, Note: "e.g. assigned, manual."},
	"IPv4 Address":     {Kind: KindText, Empty: "when VMware Tools reports none", Note: "Several addresses are joined with \", \" in one cell."},
	"IPv6 Address":     {Kind: KindText, Empty: "when VMware Tools reports none", Note: "Several addresses are joined with \", \" in one cell."},
	"Direct Path IO":   {Kind: KindBoolean},

	// vHost.
	"in Maintenance Mode": {Kind: KindBoolean},
	"Speed":               {Kind: KindInteger, Unit: "MHz", Note: "Per-core clock speed."},
	"# Cores":             {Kind: KindInteger, Note: "Physical cores across every socket."},
	"CPU usage %":         {Kind: KindDecimal, Unit: "percent", Empty: "when the host reports no CPU capacity, rather than dividing by zero", Note: "Fractional percentages are retained; RVTools 4.8.1.4 writes integers."},
	"# Memory":            {Kind: KindInteger, Unit: "MiB", Note: "Physical memory installed."},
	"Memory usage %":      {Kind: KindDecimal, Unit: "percent", Empty: "when the host reports no memory capacity, rather than dividing by zero", Note: "Fractional percentages are retained; RVTools 4.8.1.4 writes integers."},
	"# VMs total":         {Kind: KindInteger, Note: "Count of HostSystem.vm references, including templates. RVTools 4.8.1.4 excludes templates."},
	"ESX Version":         {Kind: KindText, Note: "Product version only, for example 8.0.3. RVTools 4.8.1.4 includes product name and build in this column."},
	"Vendor":              {Kind: KindText},
	"Model":               {Kind: KindText},

	// vCluster.
	"NumHosts":          {Kind: KindInteger},
	"numEffectiveHosts": {Kind: KindInteger, Note: "Hosts currently able to run VMs."},
	"TotalCpu":          {Kind: KindInteger, Unit: "MHz"},
	"NumCpuCores":       {Kind: KindInteger},
	"TotalMemory":       {Kind: KindInteger, Unit: "MiB"},
	"HA enabled":        {Kind: KindBoolean},
	"DRS enabled":       {Kind: KindBoolean},

	// vRP.
	"Resource pool":             {Kind: KindText, Note: "Inventory path of the pool."},
	"VMs":                       {Kind: KindInteger, Note: "VMs directly in this pool."},
	"vCPUs":                     {Kind: KindInteger, Note: "Sum of configured vCPUs across the VMs in this pool."},
	"CPU limit":                 {Kind: KindInteger, Unit: "MHz", Empty: "when unlimited"},
	"CPU overheadLimit":         {Kind: KindInteger, Unit: "MHz", Empty: "when vSphere does not expose one"},
	"CPU reservation":           {Kind: KindInteger, Unit: "MHz", Empty: "when vSphere does not expose one"},
	"CPU level":                 {Kind: KindText, Note: "low, normal, high or custom."},
	"CPU shares":                {Kind: KindInteger},
	"CPU expandableReservation": {Kind: KindBoolean},
	"Mem Configured":            {Kind: KindInteger, Unit: "MiB"},
	"Mem limit":                 {Kind: KindInteger, Unit: "MiB", Empty: "when unlimited"},
	"Mem overheadLimit":         {Kind: KindInteger, Unit: "MiB", Empty: "when vSphere does not expose one"},
	"Mem reservation":           {Kind: KindInteger, Unit: "MiB", Empty: "when vSphere does not expose one"},
	"Mem level":                 {Kind: KindText, Note: "low, normal, high or custom."},
	"Mem shares":                {Kind: KindInteger},
	"Mem expandableReservation": {Kind: KindBoolean},
	"Config status":             {Kind: KindText, Note: "vSphere configuration status colour: green, yellow, red or gray."},

	// vDatastore.
	"Accessible":       {Kind: KindBoolean},
	"Maintenance mode": {Kind: KindText, Empty: "when vSphere does not expose one"},

	// vSnapshot.
	"Description": {Kind: KindText, Empty: "when the snapshot has no description"},
	"Date / time": {Kind: KindDate, Empty: "when vCenter reports no creation time",
		Note: "Snapshot creation time in UTC: a zone-free date cell in XLSX and RFC3339 UTC in CSV. RVTools 4.8.1.4 writes collector-local time without a zone."},
	"Quiesced": {Kind: KindBoolean, Note: "Whether the guest filesystem was quiesced."},
	"State":    {Kind: KindText, Note: "VM power state when the snapshot was taken."},

	// vHealth.
	"Message":        {Kind: KindText, Note: "What the rule found, in the operator's terms."},
	"Message type":   {Kind: KindText, Note: "Finding severity: info, warning or critical."},
	"Category":       {Kind: KindText, Note: "Finding category: migration, availability, security, capacity or hygiene."},
	"vsfleet Rule":   {Kind: KindText, Note: "A vsfleet addition: the rule identifier that produced the finding, so a finding can be traced to its threshold. List them with `vsfleet health --list-rules`."},
	"Recommendation": {Kind: KindText, Empty: "when the rule has no remediation guidance", Note: "The recommended operator action for this rule."},
	"Evidence":       {Kind: KindText, Empty: "when the finding has no structured evidence", Note: "Measured facts rendered as field=observed (expected value), joined with semicolons."},
	"Object type":    {Kind: KindText, Note: "What the finding is about: vm, host, datastore, cluster, dvswitch or another captured resource."},

	// vsfleetCoverage.
	"Run ID":      {Kind: KindInteger, Note: "The stored assessment this export was rendered from."},
	"Run label":   {Kind: KindText, Empty: "when the run was captured without --label"},
	"Run started": {Kind: KindDate, Note: "Rendered as a date cell in XLSX and as RFC3339 UTC in CSV."},
	"Run finished": {Kind: KindDate, Empty: "while a run is unfinished",
		Note: "Rendered as a date cell in XLSX and as RFC3339 UTC in CSV."},
	"Run status": {Kind: KindText, Note: "complete, partial or failed."},
	"Context":    {Kind: KindText, Note: "The configured vsfleet context this row accounts for."},
	"Endpoint":   {Kind: KindText},
	"vCenter ID": {Kind: KindText, Note: "vCenter instance UUID, falling back to the endpoint string."},
	"Sheet":      {Kind: KindText, Note: "The worksheet this row accounts for."},
	"Collection status": {Kind: KindText,
		Note: "success, empty, failed, partial, or \"not recorded\" when the capture predates the worksheet."},
	"Item count": {Kind: KindInteger, Note: "Rows this context contributed to that worksheet."},
	"Error":      {Kind: KindText, Empty: "when nothing went wrong", Note: "Why a collection failed, or what a partial one is missing."},
}

// sheetColumns describes columns whose meaning depends on the worksheet. A
// name here shadows the shared description for that sheet only.
var sheetColumns = map[string]map[string]ColumnSpec{
	"vSource": {
		"Name":            {Kind: KindText, Empty: "when the server reports no name", Note: "AboutInfo.name: short form of the product name."},
		"OS type":         {Kind: KindText, Empty: "when the server reports none", Note: "AboutInfo.osType, for example linux-x86 or vmnix-x86."},
		"API type":        {Kind: KindText, Empty: "when the server reports none", Note: "AboutInfo.apiType: VirtualCenter for vCenter, HostAgent for a standalone ESXi host."},
		"API version":     {Kind: KindText, Empty: "when the server reports none", Note: "AboutInfo.apiVersion, dot-separated."},
		"Version":         {Kind: KindText, Empty: "when the server reports none", Note: "AboutInfo.version, dot-separated product version."},
		"Patch level":     {Kind: KindText, Empty: "when the server reports none, as older vCenter and ESXi releases do not", Note: "AboutInfo.patchLevel."},
		"Build":           {Kind: KindText, Empty: "when the server reports none", Note: "AboutInfo.build string for the server."},
		"Fullname":        {Kind: KindText, Empty: "when the server reports none", Note: "AboutInfo.fullName: complete product name including version."},
		"Product name":    {Kind: KindText, Empty: "when the server reports none", Note: "AboutInfo.licenseProductName: the license product name."},
		"Product version": {Kind: KindText, Empty: "when the server reports none", Note: "AboutInfo.licenseProductVersion: the license product version."},
		"Product line":    {Kind: KindText, Empty: "when the server reports none", Note: "AboutInfo.productLineId, for example vpx (vCenter) or embeddedEsx (ESXi)."},
		"Vendor":          {Kind: KindText, Empty: "when the server reports none", Note: "AboutInfo.vendor."},
		"VI SDK UUID":     {Kind: KindText, Note: "The stored vCenter identity of this context: AboutInfo.instanceUuid, falling back to the endpoint string when the server omitted it, exactly as every other worksheet records it."},
	},
	"vDisk": {
		"Disk":         {Kind: KindText, Note: "Virtual disk label, e.g. Hard disk 1."},
		"Disk Key":     {Kind: KindInteger, Note: "Device key of the virtual disk. Joins to the column of the same name on vPartition."},
		"Capacity MiB": {Kind: KindDecimal, Unit: "MiB", Note: "Provisioned size of the virtual disk, which is not how much of it the guest has used."},
	},
	"vPartition": {
		"Disk": {Kind: KindText, Note: "Guest filesystem mount point or drive letter, e.g. / or C:\\."},
		"Disk Key": {Kind: KindText, Empty: "on estates before vSphere 7.0, where VMware Tools reports no mapping",
			Note: "The virtual disk behind this filesystem, joining to vDisk. A single key stays numeric so it matches vDisk's own numeric cell; a volume spanning several disks names each of them. An empty cell means unknown, never disk key zero."},
		"Capacity MiB": {Kind: KindDecimal, Unit: "MiB", Note: "Size of the guest filesystem, as VMware Tools measured it. Fractional MiB are retained; RVTools 4.8.1.4 writes integers."},
		"Free MiB":     {Kind: KindDecimal, Unit: "MiB", Note: "Fractional MiB are retained; RVTools 4.8.1.4 writes integers."},
		"Free %":       {Kind: KindDecimal, Unit: "percent", Note: "Rounded to two decimals; RVTools 4.8.1.4 writes integers. A filesystem VMware Tools reports with zero capacity is given 0 rather than an empty cell, because anything summing the column would read an empty cell as full."},
	},
	"vCD": {
		"Device":               {Kind: KindText, Note: "Virtual CD/DVD device label."},
		"Device Key":           {Kind: KindInteger, Note: "vSphere virtual-device key."},
		"Connected":            {Kind: KindBoolean, Empty: "when vSphere omits connectable state"},
		"Starts Connected":     {Kind: KindBoolean, Empty: "when vSphere omits connectable state"},
		"Backing type":         {Kind: KindText, Empty: "when vSphere omits backing information"},
		"Backing path":         {Kind: KindText, Empty: "when the backing has no file path"},
		"Backing device":       {Kind: KindText, Empty: "when the backing has no host-device identity"},
		"Backing host":         {Kind: KindText, Empty: "when the backing has no host identity"},
		"Backing datastore ID": {Kind: KindText, Empty: "when the backing is not datastore-backed or vSphere omits the datastore"},
		"Backing object ID":    {Kind: KindText, Empty: "when vSphere omits the backing managed-object ID"},
		"Use auto detect":      {Kind: KindBoolean, Empty: "when the backing does not expose auto-detect state"},
		"Controller":           {Kind: KindText, Empty: "when the controller cannot be resolved"},
		"Controller label":     {Kind: KindText, Empty: "when the controller cannot be resolved"},
		"Unit number":          {Kind: KindInteger, Empty: "when vSphere does not expose one"},
	},
	"vUSB": {
		"Device":               {Kind: KindText, Note: "Virtual USB device label."},
		"Device Key":           {Kind: KindInteger, Note: "vSphere virtual-device key."},
		"Connected":            {Kind: KindBoolean, Empty: "when the persisted capture has no connection state"},
		"Vendor ID":            {Kind: KindInteger, Empty: "when vSphere reports no vendor identifier"},
		"Product ID":           {Kind: KindInteger, Empty: "when vSphere reports no product identifier"},
		"Family":               {Kind: KindText, Empty: "when vSphere reports no device families", Note: "Multiple families are joined with comma-space."},
		"Speed":                {Kind: KindText, Empty: "when vSphere reports no device speeds", Note: "Multiple speeds are joined with comma-space."},
		"Backing type":         {Kind: KindText, Empty: "when vSphere omits backing information"},
		"Backing path":         {Kind: KindText, Empty: "when the backing has no file path"},
		"Backing device":       {Kind: KindText, Empty: "when the backing has no host-device identity"},
		"Backing host":         {Kind: KindText, Empty: "when the backing has no host identity"},
		"Backing datastore ID": {Kind: KindText, Empty: "when the backing is not datastore-backed or vSphere omits the datastore"},
		"Backing object ID":    {Kind: KindText, Empty: "when vSphere omits the backing managed-object ID"},
		"Use auto detect":      {Kind: KindBoolean, Empty: "when the backing does not expose auto-detect state"},
		"Controller":           {Kind: KindText, Empty: "when the controller cannot be resolved"},
		"Controller label":     {Kind: KindText, Empty: "when the controller cannot be resolved"},
		"Unit number":          {Kind: KindInteger, Empty: "when vSphere does not expose one"},
	},
	"vDatastore": {
		"Name":         {Kind: KindText, Note: "Datastore name."},
		"Type":         {Kind: KindText, Note: "e.g. VMFS, NFS, vsan."},
		"Capacity MiB": {Kind: KindDecimal, Unit: "MiB", Note: "Total datastore capacity. Fractional MiB are retained; RVTools 4.8.1.4 writes integers."},
		"In Use MiB":   {Kind: KindDecimal, Unit: "MiB", Note: "Used datastore capacity. Fractional MiB are retained; RVTools 4.8.1.4 writes integers."},
		"Free MiB":     {Kind: KindDecimal, Unit: "MiB", Note: "Fractional MiB are retained; RVTools 4.8.1.4 writes integers."},
		"Free %":       {Kind: KindDecimal, Unit: "percent", Empty: "when the datastore reports no capacity, rather than dividing by zero", Note: "Fractional percentages are retained; RVTools 4.8.1.4 writes integers."},
		"Object ID":    {Kind: KindText, Note: "vCenter managed object reference of the datastore."},
	},
	"vCluster": {
		"Name":      {Kind: KindText, Note: "Cluster name."},
		"Object ID": {Kind: KindText, Note: "vCenter managed object reference of the cluster."},
	},
	"vRP": {
		"Name":      {Kind: KindText, Note: "Resource pool name, the last element of the Resource pool path."},
		"Status":    {Kind: KindText, Note: "vSphere overall status colour: green, yellow, red or gray."},
		"Object ID": {Kind: KindText, Note: "vCenter managed object reference of the resource pool."},
	},
	"vHost": {
		"Host":      {Kind: KindText, Note: "ESXi host name."},
		"Object ID": {Kind: KindText, Note: "vCenter managed object reference of the host."},
	},
	"vHBA": {
		"Device":           {Kind: KindText, Note: "Host bus adapter device name, for example vmhba0."},
		"Bus":              {Kind: KindInteger, Note: "Host bus number."},
		"Status":           {Kind: KindText, Note: "Adapter operational status as vSphere reports it."},
		"Model":            {Kind: KindText, Note: "Host bus adapter model."},
		"Driver":           {Kind: KindText, Empty: "when vSphere does not report a driver"},
		"Pci":              {Kind: KindText, Empty: "when vSphere does not report a PCI identifier"},
		"Storage protocol": {Kind: KindText, Note: "Storage protocol reported by the adapter; vSphere's omitted default is shown as scsi."},
		"WWNN":             {Kind: KindInteger, Empty: "for adapters that do not expose a Fibre Channel node WWN"},
		"WWPN":             {Kind: KindInteger, Empty: "for adapters that do not expose a Fibre Channel port WWN"},
		"iSCSI name":       {Kind: KindText, Empty: "for adapters that are not iSCSI, or when no iSCSI name is reported"},
		"iSCSI alias":      {Kind: KindText, Empty: "when the iSCSI adapter has no alias"},
		"Type":             {Kind: KindText, Note: "Concrete vSphere adapter type, such as HostFibreChannelHba or HostBlockHba. RVTools 4.8.1.4 uses a human-readable label, such as Block SCSI."},
		"Host":             {Kind: KindText, Note: "ESXi host that owns the adapter."},
		"Cluster":          {Kind: KindText, Empty: "for a standalone host"},
		"Object ID":        {Kind: KindText, Note: "vCenter managed object reference of the host."},
	},
	"vNIC": {
		"Device":        {Kind: KindText, Note: "Physical NIC device name, for example vmnic0."},
		"PCI":           {Kind: KindText, Empty: "when vSphere does not report a PCI identifier"},
		"Driver":        {Kind: KindText, Empty: "when vSphere does not report a driver"},
		"Mac Address":   {Kind: KindText, Empty: "when vSphere does not report a MAC address"},
		"Link speed Mb": {Kind: KindInteger, Unit: "Mb/s", Empty: "when the physical link is down or vSphere reports no link state"},
		"Duplex":        {Kind: KindBoolean, Empty: "when the physical link is down or vSphere reports no link state"},
		"Wake on LAN":   {Kind: KindBoolean, Note: "Whether the physical NIC supports wake on LAN."},
		"Switch":        {Kind: KindText, Empty: "when the physical NIC is not attached to a standard virtual switch"},
		"Host":          {Kind: KindText, Note: "ESXi host that owns the NIC."},
		"Cluster":       {Kind: KindText, Empty: "for a standalone host"},
		"Object ID":     {Kind: KindText, Note: "vCenter managed object reference of the host."},
	},
	"vSwitch": {
		"Switch":           {Kind: KindText, Note: "Standard virtual switch name."},
		"# Ports":          {Kind: KindInteger, Note: "Number of ports currently on the switch."},
		"Free Ports":       {Kind: KindInteger, Note: "Ports available for new services."},
		"MTU":              {Kind: KindInteger, Unit: "bytes", Note: "Maximum transmission unit."},
		"Uplinks":          {Kind: KindText, Empty: "when the switch has no physical uplinks", Note: "Physical NIC keys joined with comma-space."},
		"Promiscuous Mode": {Kind: KindBoolean, Empty: "when the switch does not report a security policy"},
		"Mac Changes":      {Kind: KindBoolean, Empty: "when the switch does not report a security policy"},
		"Forged Transmits": {Kind: KindBoolean, Empty: "when the switch does not report a security policy"},
		"Traffic Shaping":  {Kind: KindBoolean, Empty: "when the switch does not report a shaping policy"},
		"Host":             {Kind: KindText, Note: "ESXi host that owns the switch."},
		"Cluster":          {Kind: KindText, Empty: "for a standalone host"},
		"Object ID":        {Kind: KindText, Note: "vCenter managed object reference of the host."},
	},
	"vPort": {
		"Port Group":       {Kind: KindText, Note: "Standard-switch port group name."},
		"Switch":           {Kind: KindText, Empty: "when vSphere does not report the parent switch"},
		"VLAN":             {Kind: KindInteger, Note: "VLAN ID; 0 means untagged and 4095 means trunk mode."},
		"Promiscuous Mode": {Kind: KindBoolean, Empty: "when the computed port-group security policy omits it"},
		"Mac Changes":      {Kind: KindBoolean, Empty: "when the computed port-group security policy omits it"},
		"Forged Transmits": {Kind: KindBoolean, Empty: "when the computed port-group security policy omits it"},
		"Host":             {Kind: KindText, Note: "ESXi host that owns the port group."},
		"Cluster":          {Kind: KindText, Empty: "for a standalone host"},
		"Object ID":        {Kind: KindText, Note: "vCenter managed object reference of the host."},
	},
	"dvSwitch": {
		"Switch":                   {Kind: KindText, Note: "Distributed virtual switch name."},
		"# Ports":                  {Kind: KindInteger, Note: "Current distributed ports on the switch."},
		"Max Ports":                {Kind: KindInteger, Note: "Configured maximum number of distributed ports."},
		"MTU":                      {Kind: KindInteger, Unit: "bytes", Note: "Maximum transmission unit configured for the switch."},
		"Vendor":                   {Kind: KindText, Empty: "when the switch does not report product information"},
		"Version":                  {Kind: KindText, Empty: "when the switch does not report product information"},
		"UUID":                     {Kind: KindText, Empty: "when vSphere does not report a switch UUID"},
		"Description":              {Kind: KindText, Empty: "when the switch has no description"},
		"Contact":                  {Kind: KindText, Empty: "when the switch has no contact name"},
		"Contact detail":           {Kind: KindText, Empty: "when the switch has no contact detail"},
		"Hosts":                    {Kind: KindText, Empty: "when no hosts are members", Note: "Host names joined with comma-space."},
		"Uplink ports":             {Kind: KindText, Empty: "when no uplink port groups are reported", Note: "Uplink port-group names joined with comma-space."},
		"Link discovery protocol":  {Kind: KindText, Empty: "when the switch has no link discovery configuration"},
		"Link discovery operation": {Kind: KindText, Empty: "when the switch has no link discovery configuration"},
		"LACP version":             {Kind: KindText, Empty: "when the switch has no LACP API version"},
		"Datacenter":               {Kind: KindText, Note: "Datacenter containing the distributed switch."},
		"Object ID":                {Kind: KindText, Note: "vCenter managed object reference of the distributed switch."},
		"VI SDK UUID":              {Kind: KindText},
		"vsfleet Context":          {Kind: KindText},
	},
	"dvPort": {
		"Port":                {Kind: KindText, Note: "Distributed port-group name."},
		"Switch":              {Kind: KindText, Note: "Parent distributed virtual switch name."},
		"Key":                 {Kind: KindText, Note: "Distributed port-group key."},
		"Type":                {Kind: KindText, Empty: "when vSphere does not report a port-group binding type"},
		"Backing type":        {Kind: KindText, Empty: "when vSphere does not report a backing type"},
		"# Ports":             {Kind: KindInteger, Note: "Configured number of ports in the group."},
		"VLAN":                {Kind: KindText, Empty: "when no default VLAN specification is reported", Note: "A VLAN ID, trunk range, or pvlan value."},
		"Uplink":              {Kind: KindBoolean},
		"Allow Promiscuous":   {Kind: KindBoolean, Empty: "when the default security policy omits it"},
		"Mac Changes":         {Kind: KindBoolean, Empty: "when the default security policy omits it"},
		"Forged Transmits":    {Kind: KindBoolean, Empty: "when the default security policy omits it"},
		"Policy":              {Kind: KindText, Empty: "when no default teaming policy is reported"},
		"Notify Switch":       {Kind: KindBoolean, Empty: "when no default teaming policy is reported"},
		"Rolling Order":       {Kind: KindBoolean, Empty: "when no default teaming policy is reported", Note: "Raw vSphere rolling-order value; opposite of the failback setting."},
		"In Traffic Shaping":  {Kind: KindBoolean, Empty: "when no ingress shaping policy is reported"},
		"Out Traffic Shaping": {Kind: KindBoolean, Empty: "when no egress shaping policy is reported"},
		"Blocked":             {Kind: KindBoolean, Empty: "when the default port policy omits it"},
		"Auto expand":         {Kind: KindBoolean, Empty: "when the port group does not report auto-expansion"},
		"Active Uplink":       {Kind: KindText, Empty: "when no active uplinks are reported"},
		"Standby Uplink":      {Kind: KindText, Empty: "when no standby uplinks are reported"},
		"Logical switch UUID": {Kind: KindText, Empty: "for a port group without NSX backing"},
		"Segment ID":          {Kind: KindText, Empty: "for a port group without NSX backing"},
		"Datacenter":          {Kind: KindText, Note: "Datacenter containing the parent distributed switch."},
		"Object ID":           {Kind: KindText, Note: "vCenter managed object reference of the parent distributed switch."},
		"VI SDK UUID":         {Kind: KindText},
		"vsfleet Context":     {Kind: KindText},
	},
	"vSC_VMK": {
		"Device":          {Kind: KindText, Note: "VMkernel or service-console device, for example vmk0."},
		"Port group":      {Kind: KindText, Empty: "when the adapter is connected to a distributed or opaque network"},
		"Mac Address":     {Kind: KindText, Empty: "when vSphere does not report a MAC address"},
		"MTU":             {Kind: KindInteger, Unit: "bytes"},
		"TSO":             {Kind: KindBoolean, Empty: "when vSphere does not report TCP segmentation offload state"},
		"Netstack":        {Kind: KindText, Empty: "when vSphere does not report a network stack"},
		"DHCP":            {Kind: KindBoolean, Empty: "when the adapter has no IP configuration"},
		"IP Address":      {Kind: KindText, Empty: "when the adapter has no reported IPv4 address"},
		"Subnet mask":     {Kind: KindText, Empty: "when the adapter has no reported IPv4 configuration"},
		"Service console": {Kind: KindBoolean, Note: "True when the adapter came from HostNetworkInfo.ConsoleVnic rather than Vnic."},
		"Host":            {Kind: KindText, Note: "ESXi host that owns the adapter."},
		"Cluster":         {Kind: KindText, Empty: "for a standalone host"},
		"Object ID":       {Kind: KindText, Note: "vCenter managed object reference of the host."},
	},
	"vMultiPath": {
		"LUN":            {Kind: KindText, Note: "SCSI LUN display name, falling back to its canonical name or device name."},
		"Device path":    {Kind: KindText, Empty: "when the resolved ScsiLun has no device name"},
		"Policy":         {Kind: KindText, Empty: "when vSphere reports no multipath policy"},
		"Local disk":     {Kind: KindBoolean, Empty: "when vSphere does not report storage locality"},
		"Path count":     {Kind: KindInteger, Note: "Total paths to this LUN; paths are aggregated into one row."},
		"Active paths":   {Kind: KindInteger},
		"Standby paths":  {Kind: KindInteger},
		"Dead paths":     {Kind: KindInteger},
		"Disabled paths": {Kind: KindInteger},
		"Working paths":  {Kind: KindInteger, Note: "Paths marked as working by the path-selection policy."},
		"Host":           {Kind: KindText, Note: "ESXi host that owns the LUN paths."},
		"Cluster":        {Kind: KindText, Empty: "for a standalone host"},
		"Object ID":      {Kind: KindText, Note: "vCenter managed object reference of the host."},
	},
	"vHealth": {
		"Name":      {Kind: KindText, Note: "Name of the object the finding is about."},
		"Object ID": {Kind: KindText, Empty: "when the finding is not about a single managed object"},
	},
	"vSnapshot": {
		"Name": {Kind: KindText, Note: "Snapshot name."},
	},
	performanceSheetName: {
		"Context":            {Kind: KindText, Note: "The vsfleet context the collection ran against."},
		"vCenter ID":         {Kind: KindText, Note: "vCenter instance UUID, falling back to the endpoint string."},
		"VM":                 {Kind: KindText, Empty: "on a \"not collected\" row", Note: "VM name as vCenter reported it when the collection ran."},
		"VM ID":              {Kind: KindText, Empty: "on a \"not collected\" row", Note: "vCenter managed object reference of the VM."},
		"VM UUID":            {Kind: KindText, Empty: "when vSphere reported none"},
		"Inventory match":    {Kind: KindText, Empty: "on a \"not collected\" row", Note: "matched when this run's inventory holds the same VM ID (and instance UUID where both are known); \"instance UUID differs\" means the ID was reused by another VM; \"not in this run\" means the VM was created or removed between the capture and the collection."},
		"Counter":            {Kind: KindText, Empty: "when the VM was not sampled or the row is \"not collected\"", Note: "cpu.usage, cpu.ready, mem.active, mem.consumed, mem.balloon or mem.swapped."},
		"Unit":               {Kind: KindText, Empty: "when the VM was not sampled", Note: "percent or MiB, after normalisation from the raw vSphere counter (usage in hundredths of a percent, memory in KB, CPU ready in milliseconds per interval)."},
		"Aggregation":        {Kind: KindText, Empty: "when the VM was not sampled", Note: "What one sample is: an average over the roll-up interval, or for cpu.ready the interval sum converted to the per-vCPU percentage of the interval."},
		"Window start":       {Kind: KindDate, Empty: "on a \"not collected\" row", Note: "Start of the collected period in UTC. Rendered as a date cell in XLSX and as RFC3339 UTC in CSV."},
		"Window end":         {Kind: KindDate, Empty: "on a \"not collected\" row", Note: "End of the collected period in UTC; also when the collection ran."},
		"Interval s":         {Kind: KindInteger, Unit: "seconds", Empty: "on a \"not collected\" row", Note: "The vCenter historical roll-up interval each sample covers."},
		"Expected samples":   {Kind: KindInteger, Empty: "on a \"not collected\" row", Note: "Samples the window should hold at this interval."},
		"Successful samples": {Kind: KindInteger, Empty: "when the VM was not sampled", Note: "Samples vSphere returned a value for."},
		"Missing samples":    {Kind: KindInteger, Empty: "when the VM was not sampled", Note: "Expected minus successful. Powered-off periods, rolled-off history and counters not collected at the vCenter's statistics level all count here; missing samples are never averaged in as zero."},
		"Average":            {Kind: KindDecimal, Empty: "when Status is not ok", Note: "Mean of the successful interval averages, in Unit."},
		"Peak":               {Kind: KindDecimal, Empty: "when Status is not ok", Note: "Highest interval average, in Unit. A floor on real instantaneous demand."},
		"P95":                {Kind: KindDecimal, Empty: "when Status is not ok or fewer than 50 samples were successful", Note: "Nearest-rank 95th percentile of the interval averages."},
		"Status":             {Kind: KindText, Note: "ok, insufficient-data (too few or too sparse samples; at least 12 covering half the window), unavailable (the counter could not be read), not sampled (a budget was reached first), no VMs, or not collected."},
		"Reason":             {Kind: KindText, Empty: "when Status is ok and nothing was omitted", Note: "Why a statistic is missing, including the error vSphere returned."},
		"Sizing signal":      {Kind: KindText, Empty: "on a \"not collected\" row", Note: "Per-VM reading, repeated on each of its rows: contention-observed (CPU ready, ballooning or swapping), peaks-observed (low typical usage but high peaks), in-use, sustained-low (peaks stayed under 30% of CPU and configured memory), insufficient-data or unavailable. Evidence about the window, not a resize instruction."},
		"Signal reason":      {Kind: KindText, Empty: "on a \"not collected\" row", Note: "The measurement or gap behind the signal."},
		"Collection status":  {Kind: KindText, Empty: "on a \"not collected\" row", Note: "success, partial (a VM, request or runtime bound was reached, or a query failed) or failed for the whole collection."},
		"Source":             {Kind: KindText, Empty: "on a \"not collected\" row", Note: "The API and server the numbers came from."},
	},
}
